Feat: Enable support for VoiceOver/Safari/MacOS
w3c/aria-at-app pull request #1101
Opened 2024-05-20 20:07 UTC by gnarf

2024-05-21 17:18 UTC, howard-e requested changes
Confirmed this allows VO and Safari tests to be queued up and ran as expected. Great stuff!

I left a minor question inline about a `logging` variable.

However, the main reason I think a 2nd look should be had here is because the prompt to trigger automation when an eligible report is created seems to be missing. I would have expected to be able to simply select that when creating a `VoiceOver` report now. In fact, it is also missing for when I'm creating an NVDA report as well. I confirmed it still popped up on `development` as shown in the screenshot but didn't on this branch.

![screenshot showing option to run a newly created test plan report with a bot](https://github.com/w3c/aria-at-app/assets/7191577/e12dc85a-3a60-4344-a9b9-63213db264f7)

2024-05-21 17:49 UTC, gnarf commented on server/models/services/ModelService.js
> +    { where, attributes = [], include = [], logging, transaction }
it's not, but it's clever - if you having trouble figuring out why the SQL query isn't working passing `logging: console.log` will dump the build SQL query - I can remove it but I wanted to point it out - glad you caught it

2024-05-21 17:50 UTC, gnarf commented
> However, the main reason I think a 2nd look should be had here is because the prompt to trigger automation when an eligible report is created seems to be missing. I would have expected to be able to simply select that when creating a `VoiceOver` report now. In fact, it is also missing for when I'm creating an NVDA report as well. I confirmed it still popped up on `development` as shown in the screenshot but didn't on this branch.

Nice catch! I can take a quick look, but it's likely that the test report isn't passing the `key` property for at/brower -- Any chance you could give me more direct instructions where that popup shows up and I'll try to carve out 30 minutes a little later today to hunt this down.

2024-05-21 18:10 UTC, howard-e commented
> Any chance you could give me more direct instructions where that popup shows up and I'll try to carve out 30 minutes a little later today to hunt this down.

@gnarf sure! On `development`, it pops up anytime I'm creating a Test Plan Report which uses NVDA as the AT. So in 2 cases currently:
1. On Test Queue page, as an admin, use the `Add Test Plans to the Test Queue` section to add a report to the queue which uses `NVDA` for the AT option.
2. On the Data Management page, as an admin, using the Test Plan Report status dialog pop up to add any report which is missing and uses the `NVDA` AT.

2024-05-21 19:09 UTC, gnarf commented
https://github.com/w3c/aria-at-app/pull/1101/commits/a659c8374e004358a5d44dacdc05e06249e83e67 should fix the issue with the add and run popup:

![screenshot of interface correctly showing the add and run popup with voiceover and safari](https://github.com/w3c/aria-at-app/assets/549355/46e4768b-ea5a-43a5-8a03-59ac0d2fa200)

2024-05-21 22:15 UTC, howard-e commented on server/models/services/ModelService.js
> +    { where, attributes = [], include = [], logging, transaction }
Yep you could remove it, but very helpful to note down!

2024-05-21 22:18 UTC, howard-e reviewed
Changes look good!

Although the test failure is quite puzzling to me (because I can't get it to fail locally). It may be worth figuring out but the assertion will have to be updated to `1` anyways because of #1097 changes recently being included in `development` that do away with the `<span class=sr-only>`.

2024-05-21 23:15 UTC, gnarf commented
> Although the test failure is quite puzzling to me (because I can't get it to fail locally). It may be worth figuring out but the assertion will have to be updated to `1` anyways because of #1097 changes recently being included in `development` that do away with the `<span class=sr-only>`.

The test that was failing was on the merged branch, so it made sense I just needed to update for the new assumptions.

2024-05-22 16:04 UTC, howard-e approved these changes
Thanks for addressing the feedback!

2024-05-22 16:28 UTC, merged