feat: Include UI to manually import the latest test plan versions
w3c/aria-at-app pull request #1290
Opened 2024-12-18 18:00 UTC by howard-e

Coming from a recent discussion with Matt + CG:

>  When we merge a plan to the main” branch, I know we have a “cron” job running–it would be nice if we had an admin button to just refresh the data on the data management page. Like “Initiate GitHub Import”.

This PR does the following:
* Adds an 'Import Latest Test Plan Versions' button to the Data Management page for an admin user
* Allows navigation to the `/settings` page for the admin which will now also include the button mentioned above. It will also display the date of the latest imported test plan version

Note: Supersedes #1289 to avoid issues with commit history

2025-01-22 23:47 UTC, stalgiag requested changes
This is exciting! Really love this use of the settings page. Left some comments inline.

2025-01-22 23:47 UTC, stalgiag commented on client/components/DataManagement/index.jsx
> +        )}
I prefer only having this on the /settings page. If you disagree then perhaps the button can be somewhere else? I feel it is confusing to have it between the filter buttons and the table that they filter.

2025-01-22 23:47 UTC, stalgiag commented on client/components/UserSettings/AdminSettings.jsx
> +const AdminSettings = ({ latestTestPlanVersion, refetch }) => {
Really love this use of the settings page.

2025-01-22 23:47 UTC, stalgiag commented on client/components/UserSettings/AdminSettings.jsx
> +        <p>Use the following actions below to perform a certain function:</p>
This text feels somewhat superfluous as it is now. Perhaps it could be worthwhile to indicate that these are actions that can be performed by admins only?

2025-01-22 23:47 UTC, stalgiag commented on client/components/UserSettings/AdminSettings.jsx
> +        const response = await fetch('/api/test/import', { method: 'POST' });
I know that it would probably be a relatively significant lift to get a progress bar on this  but it is difficult to see the infinite spinner with such a long running operation. My system took a few minutes to complete the task and I was concerned that something had broken. If the progress bar would be too much work then perhaps we could add a note that "this could take a few minutes"?

2025-01-22 23:47 UTC, stalgiag commented on client/components/common/BasicThemedModal/index.jsx
> +                    : '#2ba51c' // success
Wonder if the nested ternary `getThemeColor()` could become a function since it is used twice? Would give an opportunity to use a switch or something a bit easier to read.

2025-01-22 23:47 UTC, stalgiag commented on server/util/constants.js
> -  NVDA: ['2024.4.1', '2024.1', '2023.3.3', '2023.3']
History issue?

2025-01-23 15:30 UTC, howard-e commented on client/components/DataManagement/index.jsx
> +        )}
I'm not a big fan of it here either. I tried to plug it in mainly because of the original request being to have the button on the Data Management page but I feel it more fitting by itself on the Settings page. So removing here isn't an issue to me!

2025-01-23 15:31 UTC, howard-e commented on client/components/UserSettings/AdminSettings.jsx
> +        const response = await fetch('/api/test/import', { method: 'POST' });
Seems fair!

2025-01-23 15:31 UTC, howard-e commented on server/util/constants.js
> -  NVDA: ['2024.4.1', '2024.1', '2023.3.3', '2023.3']
Ahh perhaps. Good catch!

2025-01-23 16:35 UTC, howard-e commented on server/util/constants.js
> -  NVDA: ['2024.4.1', '2024.1', '2023.3.3', '2023.3']
https://github.com/w3c/aria-at-app/pull/1290/commits/6d906689da6e7c67b75cf75bb1a6685c27d26f91

2025-01-23 16:35 UTC, howard-e commented on client/components/UserSettings/AdminSettings.jsx
> +        const response = await fetch('/api/test/import', { method: 'POST' });
Opted to add a note instead in https://github.com/w3c/aria-at-app/pull/1290/commits/a9dae3ab42039199b8be4906613f43df803f4012. Let me know if this feels better to you

2025-01-23 16:35 UTC, howard-e commented on client/components/UserSettings/AdminSettings.jsx
> +        <p>Use the following actions below to perform a certain function:</p>
Should be addressed in https://github.com/w3c/aria-at-app/pull/1290/commits/f5193e99d415fd6276f79e7d40c333522fabcc4f

2025-01-28 00:08 UTC, stalgiag commented on client/components/UserSettings/AdminSettings.jsx
> +        const response = await fetch('/api/test/import', { method: 'POST' });
Yep this feels much better. Thanks!

2025-01-28 00:09 UTC, stalgiag commented on client/components/common/BasicThemedModal/index.jsx
> +                    : '#2ba51c' // success
Nice!

2025-01-28 00:10 UTC, stalgiag approved these changes
This is great now! Thanks for addressing the feedback.

2025-01-28 15:06 UTC, merged