Add tests and their results as return values from run API calls
w3c/aria-at-app pull request #177
Opened 2020-10-08 00:10 UTC by rmeritz

See jsdoc for more information on the spec followed. It was largely cribbed from the existing `getTestsForRunsForCycle` cycle service

2020-10-08 16:55 UTC, spectranaut requested changes
One more detail of the tests needs to be accounted for! Otherwise looking really good.

2020-10-08 16:55 UTC, spectranaut commented on server/services/RunService.js
> +            tests: run.ApgExample.Tests.reduce((acc, test) => {
getting the tests for a run is a little more complicated that this -- you need to use TestToAt to make sure that any test applies to a run with a specific AT. Not all test files for an APG pattern apply to all ATs.

For example, of all Checkbox APG example tests, 2 of them do not apply to VoiceOver, so those test need to be skipped in all the runs of VoiceOver.

2020-10-08 16:55 UTC, spectranaut commented on server/services/RunService.js
> +                        testResult => testResult.run_id == run.id
this might take care for that for results? but you still will see a test with no results.

2020-10-13 16:03 UTC, evmiguel reviewed
Reviewed, waiting for Val's requests to be fulfilled.

2020-10-13 19:27 UTC, rmeritz commented
@spectranaut || @evmiguel - I fixed the issue with non-relavant tests being included in the results. See the last commit.

2020-10-13 19:52 UTC, evmiguel approved these changes

2020-10-13 19:52 UTC, evmiguel commented on server/services/RunService.js
> +                (test.TestToAts || []).some(
This change should handle the change request @spectranaut

2020-10-13 20:42 UTC, merged