Add Descriptive Headings to Test Instructions and Criteria
w3c/aria-at-app pull request #379
Opened 2021-12-09 13:41 UTC by jkva

This PR addresses the following item from PAC's "ARIA-AT App Screen Reader Accessibility Observations" document:

> Within the content of a test, the lists of instructions, commands and assertions do not have accessible names, to help screen reader users understand their purpose and distinguish between the many lists on the page.

@jscholes this PR only covers the headings for test instructions and success criteria; the assertions table heading is covered by #375.

---
Effective changes:

- add a `h2` before "Test Instructions"
- describe the instructions `ol` using idref
- add a `h2` before "Success Criteria"
- describe the criteria `ol` using idref

2021-12-09 20:03 UTC, jscholes requested changes
@jkva I'm concerned about the heading hierarchy overlaps between this, https://github.com/w3c/aria-at-app/pull/377, and https://github.com/w3c/aria-at-app/pull/376.  For instance, if https://github.com/w3c/aria-at-app/pull/376 increases the level of what used to be a duplicate `h1`, it seems like the headings introduced in this PR (and maybe https://github.com/w3c/aria-at-app/pull/377) should be higher?  May be worth a double check.

2021-12-10 08:43 UTC, jkva commented
@jscholes I've been aware of that as some of these PRs do indeed intersect. I'll merge a few together in a general "Heading Structure Improvements" PR.

2022-02-02 16:48 UTC, alflennik commented
Just let us know when you think this is ready for our review @jkva.

2022-02-03 12:58 UTC, jkva commented
@alflennik given the overarching PR #396 was closed (since some other PRs it contained have since been merged), this PR should still be merged, hence please review.

2022-02-03 17:17 UTC, evmiguel approved these changes

2022-02-03 17:17 UTC, merged