WIP: Unexpected behavior note
w3c/aria-at-app pull request #450
Opened 2022-07-26 04:12 UTC by alflennik

2022-08-11 18:14 UTC, evmiguel commented on server/resolvers/TestResultOperations/saveTestResultCommon.js
> +        if (!unexpectedBehaviorNote && unexpectedBehavior.id === 'OTHER') {
Non-blocking: Are we still expecting a behavior note to be filled when OTHER? I thought the note would be decoupled from all undesirable behaviors.

2022-08-11 19:46 UTC, evmiguel commented on client/resources/aria-at-test-io-format.mjs
> +        { description: 'Other', requireExplanation: true },
Same question here. Is Other supposed to be coupled to the explanation?

2022-08-11 20:13 UTC, evmiguel commented on client/resources/aria-at-harness.mjs
> +          // TODO: Figure out why this isn't appearing
Looks like this is appearing!

2022-08-11 20:27 UTC, evmiguel requested changes
Looking good! There's a bug in the form validation. 

https://user-images.githubusercontent.com/2789098/184236046-840ae019-fada-4e5f-be99-bd0b0fc83652.mov

UPDATE: Actually, the bug persists when switching between No and Yes.

2022-08-11 20:28 UTC, evmiguel commented on client/resources/aria-at-test-run.mjs
> +            description: '(required)',
I'm not seeing this. How do I get to this state?

2022-08-11 20:29 UTC, evmiguel commented on client/resources/aria-at-test-run.mjs
> +                description: resultUnexpectedBehavior.behaviors.some(
I'm not seeing this. How do I get to this state?

2024-03-12 18:04 UTC, alflennik commented
Superseded by https://github.com/w3c/aria-at-app/pull/596

2024-03-12 18:04 UTC, closed without merging