Add Test Plan Management page
w3c/aria-at-app pull request #470
Opened 2022-11-10 15:35 UTC by howard-e

This adds the initial foundation for the test plan management page. This is based on recent discussions to advance the Test Plan Reports' phase from Draft -> Candidate -> Recommended grouped by the ATs.
eg. Moving Alert Example to Candidate Phase for JAWS, NVDA & VoiceOver on macOS all at once.

How to run:
1. `yarn install`
2. Run the application and sign in as an admin
3. Navigate to `localhost:3000/test-management`

**Note: This builds onto #461. We can change the base branch back to `main` once that's merged**

2022-11-14 20:39 UTC, evmiguel requested changes
Well done, @howard-e! The disclosure component is slick and the new Test Management system is implemented very well. One blocker is the statuses, and it's probably a larger conversation around how we deal with the `Recommended` state. 

@s3ththompson could you chime in on whether we can use `In Review` as `Candidate` and `Finalized` as `Recommended`?

2022-11-21 20:05 UTC, evmiguel requested changes
New phase changes look good! Only one request, and it's good to go.

2022-11-21 20:05 UTC, evmiguel commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                )
`vendorReviewStatus: 'READY'` should go here

2022-11-21 20:05 UTC, evmiguel commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                vendorReviewStatus: 'READY'
Remove `vendorReviewStatus`

2022-11-21 20:08 UTC, evmiguel commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                )
The `vendorReviewStatus` gets set when the report goes to the Candidate phase. Once it's been recommended, the `vendorReviewStatus` should be approved.

2022-11-21 20:10 UTC, evmiguel commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                )
```suggestion
                ),
                vendorReviewStatus: 'READY'
```

2022-11-21 20:10 UTC, evmiguel commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                vendorReviewStatus: 'READY'
```suggestion
                vendorReviewStatus: 'APPROVED'
```

2022-11-21 20:28 UTC, evmiguel commented on client/components/TestManagement/StatusSummaryRow/index.jsx
> +    if (testPlanReports.every(i => i.status === 'RECOMMENDED'))
Should this be `testPlanReports.every(i => i.status === 'RECOMMENDED') || testPlanReports.every(i => i.vendorReviewStatus === 'APPROVED')` ?

Or should the status of the report be moved to `RECOMMENDED` when the vendor approves the report?

2022-11-21 21:52 UTC, howard-e commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                )
Good catch!

2022-11-21 21:54 UTC, howard-e commented on server/resolvers/TestPlanReportOperations/updateStatusResolver.js
> +                vendorReviewStatus: 'READY'
Thanks!

2022-11-22 20:05 UTC, evmiguel approved these changes

2022-11-22 20:05 UTC, evmiguel commented on client/components/ManageTestQueue/index.jsx
> +            {/*</Container>*/}
```suggestion
```

2022-11-22 20:20 UTC, merged