Button and Dialog for Covered AT on DataManagement
w3c/aria-at-app pull request #742
Opened 2023-08-10 19:17 UTC by stalgiag

## Summary

This PR replaces the current listing of ATs in the Covered AT column on the Data Management page with a button that lists an inventory of covered ATs (simple now due to only supporting "Desktop Screenreaders" currently) and opens a dialog with all of the unique AT + AT version combos.

### Issues resolved

resolves #656

2023-08-14 17:58 UTC, stalgiag commented
After a conversation with @alflennik, we decided that this list likely should be unique ATs not unique AT + AT Version combos. I will make this change on Wednesday when I am back on the project.

2023-08-16 17:18 UTC, alflennik requested changes
I tested it in NVDA and it worked great. Nice.

2023-08-16 17:18 UTC, alflennik commented on client/components/DataManagement/CoveredAtListDialogWithButton/index.jsx
> +                <strong>{ats.length} Desktop</strong> Screenreaders
Would it be possible to make this two words?

I know this probably clashes with the specified design. Just to back up the suggestion a little bit, I googled `"screen readers"` and got 80 million results, and then googled `"screenreaders"` and got 200K results. In other words, the term screen readers as two words is 400 times as common.

2023-08-16 17:18 UTC, alflennik commented on client/components/DataManagement/CoveredAtListDialogWithButton/index.jsx
> +            />
Would it be possible to reduce slightly the amount of padding in the modal?

2023-08-16 23:38 UTC, howard-e approved these changes
Looks good!

2023-08-17 16:12 UTC, alflennik approved these changes
Looks great!

2024-06-26 17:16 UTC, stalgiag commented
Closing this as I don't think it's relevant to the current UI anymoore

2024-06-26 17:16 UTC, closed without merging