Ensure that the In Review filter captures all test plans that have a draft review
w3c/aria-at-app pull request #896
Opened 2024-01-22 22:38 UTC by evmiguel

This PR addresses #884, where the app was not capturing all the test plans that contained In Draft reviews.

2024-01-29 22:39 UTC, stalgiag requested changes
We discussed separately but noting here also. I think the todo requires that a test plan row is visible if it has ANY test plan version in any of the selected phases. This probably warrants rewriting the hook so that it doesn't rely on overall test plan phase at all.

2024-02-05 23:14 UTC, stalgiag commented on client/components/DataManagement/filterSortHooks.js
> +                    );
The way that the reference is being accessed/modified is a little slippery to me here.

I wonder if something without the temporary var could also work well.

```
  // Ensure the array exists or initialize it directly before pushing the new phase
  activeTestPlanVersionsByPhase[testPlan.id] = activeTestPlanVersionsByPhase[testPlan.id] ?? [];
  activeTestPlanVersionsByPhase[testPlan.id].push(derivedPhase);

```

2024-02-05 23:18 UTC, stalgiag commented on docs/database.md
> +yarn workspace server db-import-tests:test -c d34eddbb8e751f07bd28d952de15fa7fe5f07353;
Good idea but I think it makes sense to keep these in [Howard's separate PR](https://github.com/w3c/aria-at-app/pull/911)

2024-02-05 23:20 UTC, stalgiag approved these changes
Nice! I am impressed by how surgical these changes are. I think the data structure with the overall phase followed by the active test plan versions sorted by phase is a good call. Tested with two different DB snapshots and am able to filter the table so that each row displays if it has any test plan version active in the selected filter phase.

Two tiny requests for changes inline but I am approving since they shouldn't be blockers.

 Thanks for this!

2024-02-07 18:58 UTC, alflennik reviewed
I verified that the change works perfectly! Thanks for going beyond the letter of the task and applying the fix to every phase 🙏. I haven't approved yet because I don't want to merge until you get back to Stalgia about her questions, especially the one about the changes to the database scripts. Additionally there is a conflict will need be resolved before I can merge.

2024-02-08 15:33 UTC, evmiguel commented
Thank you @stalgiag and @alflennik! I've addressed your feedback, and the merge conflicts have been resolved.

2024-02-08 16:40 UTC, alflennik approved these changes

2024-02-08 16:41 UTC, merged