Update Un-assign User button and Messages
w3c/aria-at-app pull request #909
Opened 2024-02-05 15:52 UTC by evmiguel

This PR addresses #830 and aims to clarify that un-assigning a user will delete their Test Plan Run

2024-02-07 18:43 UTC, alflennik requested changes
Hi Erika, I'm sorry but I just recently changed this file in a way that would be incompatible with your changes. Would you be able to implement this using the `aria-live-bug` as a base? PR is here: https://github.com/w3c/aria-at-app/pull/894

2024-02-08 15:57 UTC, evmiguel commented
@alflennik sure thing!

2024-02-12 19:31 UTC, evmiguel commented
@alflennik I updated the alert message with the new changes.

2024-02-14 19:01 UTC, alflennik approved these changes
Looks great visually and I tested this in NVDA and VoiceOver as well. All cases do seem to be improved and the action of the button is definitely more clear.

2024-02-15 15:07 UTC, howard-e approved these changes
LGTM! This was a useful change to promote clarity, thanks!

2024-02-15 15:07 UTC, merged